name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Enable caching for faster builds
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build:gh-pages
        env:
          GITHUB_PAGES: 'true'
          GITHUB_ACTIONS: 'true'
          NODE_ENV: 'production'

      # Create important files and optimize assets
      - name: Post-build optimizations
        run: |
          # Create .nojekyll
          touch dist/.nojekyll
          
          # Create _headers file for caching
          echo "/*" > dist/_headers
          echo "  Cache-Control: public, max-age=31536000" >> dist/_headers
          echo "/index.html" >> dist/_headers
          echo "  Cache-Control: public, max-age=0, must-revalidate" >> dist/_headers
          
          # Verify and optimize assets
          find dist -type f -name "*.js" -exec gzip -k {} \;
          find dist -type f -name "*.css" -exec gzip -k {} \;

      # Comprehensive build verification
      - name: Verify build output
        run: |
          echo "=== Build Output Summary ==="
          echo "Directory structure:"
          tree dist -L 2
          
          echo "=== Asset sizes ==="
          find dist -type f -exec du -h {} \;
          
          echo "=== Gzipped assets ==="
          find dist -name "*.gz" -exec ls -lh {} \;
          
          echo "=== Cache headers ==="
          cat dist/_headers

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
